# Generated by Django 4.0 on 2021-12-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Technology', max_length=255)),
                ('sub_domain', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('storage_type_name', models.CharField(max_length=255)),
                ('storage_type_cost', models.IntegerField(default=0)),
                ('other_cost', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Technology.technology', to_field='sub_domain')),
            ],
        ),
    ]
