# Generated by Django 4.0 on 2021-12-25 11:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuseradminconfig_usermanager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuseradminconfig',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
