# Generated by Django 4.0 on 2021-12-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customuseradminconfig',
            managers=[
            ],
        ),
    ]
